/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UIPackage;

/**
 *
 * @author ahmetcan
 */
public class BiletSatisGUI extends javax.swing.JPanel {

    AnaSayfaGUI parent;
    /**
     * Creates new form BiletSatisGUI
     */
    public BiletSatisGUI(AnaSayfaGUI parent) {
        initComponents();
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        baslangicCombo = new javax.swing.JComboBox();
        bitisCombo = new javax.swing.JComboBox();
        tarihText = new javax.swing.JTextField();
        biletLabel = new javax.swing.JLabel();
        başlangıçLabel = new javax.swing.JLabel();
        bitisLabel = new javax.swing.JLabel();
        tarihLabel = new javax.swing.JLabel();
        seferSorgulaButton = new javax.swing.JButton();

        setLayout(null);

        add(baslangicCombo);
        baslangicCombo.setBounds(12, 106, 105, 27);

        add(bitisCombo);
        bitisCombo.setBounds(123, 106, 96, 27);
        add(tarihText);
        tarihText.setBounds(237, 106, 127, 27);

        biletLabel.setText("Başlangıç, Bitiş ve Tarih Bilgilerini Giriniz");
        add(biletLabel);
        biletLabel.setBounds(83, 29, 253, 17);

        başlangıçLabel.setText("Başlangıç");
        add(başlangıçLabel);
        başlangıçLabel.setBounds(27, 86, 61, 17);

        bitisLabel.setText("Bitiş");
        add(bitisLabel);
        bitisLabel.setBounds(151, 86, 38, 17);

        tarihLabel.setText("Tarih");
        add(tarihLabel);
        tarihLabel.setBounds(280, 86, 31, 17);

        seferSorgulaButton.setText("Sorgula");
        add(seferSorgulaButton);
        seferSorgulaButton.setBounds(264, 189, 100, 29);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox baslangicCombo;
    private javax.swing.JLabel başlangıçLabel;
    private javax.swing.JLabel biletLabel;
    private javax.swing.JComboBox bitisCombo;
    private javax.swing.JLabel bitisLabel;
    private javax.swing.JButton seferSorgulaButton;
    private javax.swing.JLabel tarihLabel;
    private javax.swing.JTextField tarihText;
    // End of variables declaration//GEN-END:variables
}
