/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UIPackage;

/**
 *
 * @author ahmetcan
 */
public class BiletSatisGUI extends javax.swing.JPanel {

    AnaSayfaGUI parent;
    /**
     * Creates new form BiletSatisGUI
     */
    public BiletSatisGUI(AnaSayfaGUI parent) {
        initComponents();
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        baslangicCombo = new javax.swing.JComboBox();
        bitisCombo = new javax.swing.JComboBox();
        tarihText = new javax.swing.JTextField();
        biletLabel = new javax.swing.JLabel();
        başlangıçLabel = new javax.swing.JLabel();
        bitisLabel = new javax.swing.JLabel();
        tarihLabel = new javax.swing.JLabel();
        seferSorgulaButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add(baslangicCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 106, 105, -1));

        add(bitisCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 106, 96, -1));
        add(tarihText, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 106, 127, -1));

        biletLabel.setText("Başlangıç, Bitiş ve Tarih Bilgilerini Giriniz");
        add(biletLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 29, -1, -1));

        başlangıçLabel.setText("Başlangıç");
        add(başlangıçLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 86, -1, -1));

        bitisLabel.setText("Bitiş");
        add(bitisLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 86, 38, -1));

        tarihLabel.setText("Tarih");
        add(tarihLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 86, -1, -1));

        seferSorgulaButton.setText("Sorgula");
        add(seferSorgulaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 189, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox baslangicCombo;
    private javax.swing.JLabel başlangıçLabel;
    private javax.swing.JLabel biletLabel;
    private javax.swing.JComboBox bitisCombo;
    private javax.swing.JLabel bitisLabel;
    private javax.swing.JButton seferSorgulaButton;
    private javax.swing.JLabel tarihLabel;
    private javax.swing.JTextField tarihText;
    // End of variables declaration//GEN-END:variables
}
