/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UIPackage;

/**
 *
 * @author ahmetcan
 */
public class CheckinGUI extends javax.swing.JPanel {

    /**
     * Creates new form CheckinGUI
     */
    public CheckinGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkinLabel = new javax.swing.JLabel();
        biletIdText = new javax.swing.JTextField();
        musteriIdText = new javax.swing.JTextField();
        koltukNumarasiText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        musteriIdLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        biletIdLabel = new javax.swing.JLabel();

        checkinLabel.setText("Lütfen Bilet İd Müşteri İd ve Koltuk Numarası Giriniz");

        musteriIdLabel.setText("Müşteri Id");

        jLabel3.setText("Koltuk Numarası");

        biletIdLabel.setText("Bilet Id");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(biletIdLabel)
                        .addGap(84, 84, 84)
                        .addComponent(musteriIdLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(biletIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(musteriIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(koltukNumarasiText, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(140, 140, 140))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(checkinLabel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(checkinLabel)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(musteriIdLabel)
                    .addComponent(jLabel3)
                    .addComponent(biletIdLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(koltukNumarasiText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(musteriIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(biletIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(165, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel biletIdLabel;
    private javax.swing.JTextField biletIdText;
    private javax.swing.JLabel checkinLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField koltukNumarasiText;
    private javax.swing.JLabel musteriIdLabel;
    private javax.swing.JTextField musteriIdText;
    // End of variables declaration//GEN-END:variables
}
