/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UIPackage;

import java.awt.BorderLayout;
import javax.swing.JFrame;

/**
 *
 * @author ahmetcan
 */
public class GirisSayfasiGUI extends javax.swing.JPanel {
    AnaSayfaGUI parent;
    /**
     * Creates new form GirisSayfasiGUI
     */
    public GirisSayfasiGUI(AnaSayfaGUI parent) {
        initComponents();
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        girisLabel = new javax.swing.JLabel();
        girisIDText = new javax.swing.JTextField();
        sistemYoneticisiGirisButton = new javax.swing.JButton();
        satisElemaniGirisButton = new javax.swing.JButton();

        girisLabel.setText("Lütfen Giriş Yapınız");

        sistemYoneticisiGirisButton.setText("Sistem Yöneticisi Giriş");
        sistemYoneticisiGirisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sistemYoneticisiGirisButtonActionPerformed(evt);
            }
        });

        satisElemaniGirisButton.setText("Satış Elemanı Giriş");
        satisElemaniGirisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satisElemaniGirisButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(sistemYoneticisiGirisButton)
                        .addGap(35, 35, 35)
                        .addComponent(satisElemaniGirisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(girisIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(girisLabel)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(girisLabel)
                .addGap(18, 18, 18)
                .addComponent(girisIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sistemYoneticisiGirisButton)
                    .addComponent(satisElemaniGirisButton))
                .addContainerGap(134, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sistemYoneticisiGirisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sistemYoneticisiGirisButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sistemYoneticisiGirisButtonActionPerformed

    private void satisElemaniGirisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satisElemaniGirisButtonActionPerformed
        // TODO add your handling code here:
        parent.remove(this);
       
        BiletSatisGUI biletSatisGUI = new BiletSatisGUI(parent);
        parent.setPanel(biletSatisGUI);
        
        
        
        
    }//GEN-LAST:event_satisElemaniGirisButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField girisIDText;
    private javax.swing.JLabel girisLabel;
    private javax.swing.JButton satisElemaniGirisButton;
    private javax.swing.JButton sistemYoneticisiGirisButton;
    // End of variables declaration//GEN-END:variables
}
