/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UIPackage;

/**
 *
 * @author ahmetcan
 */
public class MenuPanel extends javax.swing.JPanel {
    AnaSayfaGUI parent;
    /**
     * Creates new form MenuPanel
     */
    public MenuPanel(AnaSayfaGUI parent) {
        initComponents();
        this.parent = parent;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cikisButton = new javax.swing.JButton();
        yeniSorguButton = new javax.swing.JButton();
        checkinButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(254, 184, 58));

        cikisButton.setText("Çıkış");
        cikisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisButtonActionPerformed(evt);
            }
        });

        yeniSorguButton.setText("Yeni Sorgu");
        yeniSorguButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yeniSorguButtonActionPerformed(evt);
            }
        });

        checkinButton.setText("Check-In ");
        checkinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkinButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(yeniSorguButton)
                .addGap(43, 43, 43)
                .addComponent(checkinButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(cikisButton)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkinButton)
                    .addComponent(cikisButton)
                    .addComponent(yeniSorguButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cikisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisButtonActionPerformed
        // TODO add your handling code here:
        parent.remove(this);
        parent.remove(parent.currentPanel);
        GirisSayfasiGUI girisSayfasi = new GirisSayfasiGUI(parent);
        parent.setPanel(girisSayfasi);
        
    }//GEN-LAST:event_cikisButtonActionPerformed

    private void yeniSorguButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yeniSorguButtonActionPerformed
        // TODO add your handling code here:
        parent.remove(this);
        parent.remove(parent.currentPanel);
        BiletSatisGUI biletSatis = new BiletSatisGUI(parent);
        parent.setPanel(biletSatis);
    }//GEN-LAST:event_yeniSorguButtonActionPerformed

    private void checkinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkinButtonActionPerformed
        // TODO add your handling code here:
        parent.remove(this);
        parent.remove(parent.currentPanel);
        CheckinGUI checkin = new CheckinGUI();
        parent.setPanel(checkin);
    }//GEN-LAST:event_checkinButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkinButton;
    private javax.swing.JButton cikisButton;
    private javax.swing.JButton yeniSorguButton;
    // End of variables declaration//GEN-END:variables
}
