/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UIPackage;

import Controller.Register;

/**
 *
 * @author ahmetcan
 */
public class UcusEklemeGUI extends javax.swing.JFrame {

    /**
     * Creates new form UcusEklemeGUI
     */
    private Register register;
    AnaSayfaGUI parent;
    public UcusEklemeGUI(AnaSayfaGUI parent) {
        initComponents();
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ucusEkleLabel = new javax.swing.JLabel();
        ucakIdCombo = new javax.swing.JComboBox();
        ucakIdLabel = new javax.swing.JLabel();
        pilotLabel = new javax.swing.JLabel();
        hostesLabel = new javax.swing.JLabel();
        pilotCombo = new javax.swing.JComboBox();
        hostesCombo = new javax.swing.JComboBox();
        tarihLabel = new javax.swing.JLabel();
        tarihLanbel = new javax.swing.JLabel();
        ucusEkleTarih = new javax.swing.JTextField();
        saatText = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        ucakLabel = new javax.swing.JLabel();
        ucusEkleButton = new javax.swing.JButton();
        buisnessFiyatText = new javax.swing.JTextField();
        ekonomikFiyatText = new javax.swing.JTextField();
        buisnessFiyatLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        seferIdText = new javax.swing.JTextField();
        seferIdLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ucusEkleLabel.setText("Lütfen Uçuş Bilgilerini Ekleyiniz");

        ucakIdCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ucakIdLabel.setText("Ucak Id");

        pilotLabel.setText("Pilot");

        hostesLabel.setText("Hostes");

        pilotCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        hostesCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tarihLabel.setText("Tarih");

        tarihLanbel.setText("Saat");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ucakLabel.setText("Uçak");

        ucusEkleButton.setText("Uçuş Kaydet");
        ucusEkleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ucusEkleButtonActionPerformed(evt);
            }
        });

        buisnessFiyatLabel.setText("Buisness Fiyat");

        jLabel2.setText("Ekonomik Fiyat");

        seferIdLabel.setText("Sefer Id");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(ucusEkleLabel))
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(ucakIdLabel)
                .addGap(190, 190, 190)
                .addComponent(seferIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(ucakIdCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(seferIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(pilotLabel)
                .addGap(171, 171, 171)
                .addComponent(hostesLabel))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(pilotCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(hostesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(tarihLabel))
                    .addComponent(ucusEkleTarih, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(tarihLanbel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(saatText, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(ucakLabel)
                .addGap(100, 100, 100)
                .addComponent(buisnessFiyatLabel)
                .addGap(59, 59, 59)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(buisnessFiyatText, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(ekonomikFiyatText, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addComponent(ucusEkleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(ucusEkleLabel)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ucakIdLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(seferIdLabel)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ucakIdCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(seferIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pilotLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(hostesLabel)))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pilotCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hostesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(tarihLabel)
                        .addGap(0, 0, 0)
                        .addComponent(ucusEkleTarih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tarihLanbel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(saatText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ucakLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buisnessFiyatLabel)
                            .addComponent(jLabel2))))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buisnessFiyatText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ekonomikFiyatText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(ucusEkleButton))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ucusEkleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ucusEkleButtonActionPerformed
        // TODO add your handling code here:
        int ucakId = (Integer)ucakIdCombo.getSelectedItem();
      
        int pilotId = (Integer)pilotCombo.getSelectedItem();
        int hostesId = (Integer)hostesCombo.getSelectedItem();
        String tarih = ucusEkleTarih.getText();
        String saat = saatText.getText();
        int buisnessFiyat = Integer.parseInt(buisnessFiyatText.getText());
        int ekomoikFiyat = Integer.parseInt(ekonomikFiyatText.getText());
        int seferId = Integer.parseInt(seferIdText.getText());
        register.ucusOlusturBaslat(ucakId, seferId, pilotId,hostesId,tarih,saat,buisnessFiyat,ekomoikFiyat);
        
    }//GEN-LAST:event_ucusEkleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UcusEklemeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UcusEklemeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UcusEklemeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UcusEklemeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
     
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buisnessFiyatLabel;
    private javax.swing.JTextField buisnessFiyatText;
    private javax.swing.JTextField ekonomikFiyatText;
    private javax.swing.JComboBox hostesCombo;
    private javax.swing.JLabel hostesLabel;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox pilotCombo;
    private javax.swing.JLabel pilotLabel;
    private javax.swing.JTextField saatText;
    private javax.swing.JLabel seferIdLabel;
    private javax.swing.JTextField seferIdText;
    private javax.swing.JLabel tarihLabel;
    private javax.swing.JLabel tarihLanbel;
    private javax.swing.JComboBox ucakIdCombo;
    private javax.swing.JLabel ucakIdLabel;
    private javax.swing.JLabel ucakLabel;
    private javax.swing.JButton ucusEkleButton;
    private javax.swing.JLabel ucusEkleLabel;
    private javax.swing.JTextField ucusEkleTarih;
    // End of variables declaration//GEN-END:variables
}
